{% set name = "uritools" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 405917a31ce58a57c8ccd0e4ea290f38baf2f4823819c3688f5331f1aee4ccb0

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - uritools

  commands:
    - python -m unittest discover

  source_files:
    - tests

about:
  home: https://github.com/tkem/uritools/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse'
  dev_url: https://github.com/tkem/uritools/
  doc_url: http://pythonhosted.org/uritools/

extra:
  recipe-maintainers:
    - ltalirz
