{% set name = "uritools" %}
{% set version = "2.2.0" %}
{% set sha256 = "80e8e23cafad54fd85811b5d9ba0fc595d933f5727c61c3937945eec09f99e2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipaddress  # [py27]

test:
  imports:
    - uritools

  commands:
    - python -m unittest discover

  source_files:
    - tests

about:
  home: https://github.com/tkem/uritools/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse'
  dev_url: https://github.com/tkem/uritools/
  doc_url: http://pythonhosted.org/uritools/

extra:
  recipe-maintainers:
    - ltalirz
