travis:
  secure:
    BINSTAR_TOKEN: WpiLwl0MWbOWSraKJDQD8pVok21S+H8woMs6G+KId3OVzAFV4aOKH4ZQZeTX0V3RzFY0xunFP+8JbgUXqvLwENWVSzqZa9p+AcumMfQ2/BSvoJBop108W88plEnwAzOInKJqhC+V4gpW4BjfIKVGWQWwM4nsW6g+KbD28FBV+bNFSGuocsvs2PPLKh0APrvdK+dlyZ1K8dXMh+DdXRK2Cbw1Z/lUoPFoRm1nueyEFutJgOBeRoVFBtS/B1JwAzlDE6Jx5NpWMMy7mN/a8Py5Ohj8mMZA+27NOW+b29OkAg1qmmI5mvmtT4CUMcCSXGog9i4goGTL8/UKbdh8kO8DC5tQACAG/fllFWUtWwpo6kGoFPTijW04hdaSSyxBelG8Ph7syn/0zlKvSP3e9ZgdeYBz1zDPW2PP62ecViiRV7WPXuZAu1+VvE5X8BQxO9LuuoLdbE1sTgM/f0MM8zHywZBYvq7Ogu1feNzC6g1McTIC+mISh3JUkh7M9g8b4p6OY9rEwwucchnIWXe7H5cGwEsrjd/MviH+yzxQA8L8OBseedNMYHcXAgFboMAsh/ubJG2rwH7zF7IDTZJIGYUlOiZzbrSRzX+4B24PuBF0Uwy9gwvjZhZnqfOI+ZWa+AQ+KXvCZhOK0rzCwo1kQBPgiOGJDwqkDwDq8zotzm0GQII=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
