travis:
  secure:
    BINSTAR_TOKEN: KUI+aZXBAKG+UR8tM88uDl+WZ4X+CJpxHHhvCoA23ehBPD1Wk0Bf0vKQ+PWe40ZaqC52oJase+7sRODDPVOZxhJ1AUZirnv4SPuOJzBmWdIKH7O66V1DpG8PkevR1JkVCHVAhG4599JcwBb7RHOsX18pqsDrAprCoUV5zPn9nLLAKTjUxD74WJTHNVmBSW4d6peNGAdqcGpL2qqu/ffjzIk/t3YcGKpR41HNJGpAJP1Snfptyu3MPHu6bkY9mLb3Y5CEVnScmxtur6+nleJ7NT7219vTm89c56IUK8GPGLmGguQla9/rpHuGsx6BtdRow+6C55HoSKE3KUFP4kAfOVM490xDgyCHbXQsgVuFIQmsrAHZkdyooimLmBRIzZOkr/RxYpPVyAkfDTJhbJKyHMI9ZYL2tSZFXLdb/7zq0YWMvwxEADQpMp9sT3qYJ8JEeXW4eg4KARef8z8//Fl9E878ui6nLKLWzunpQFdKKAunpICe+6UKxUHyx8WKGT/Bc8Fs+k4Sl/2l9RSNMuvnoKhgfXAIIpxjPGbd24zusYZC9oFsCx51kQjnfTUIKiS/2Nd4MZ8tA8e5u5uEMYqeX5Ch1KaE3cwZPHkfk5n5q6mG/FiF/2rsuv27T093d+wtCznVE7C5IwK2HzI37BDeOAd+jiOnmeWw/hSEJv37njM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
